# Generated by Django 5.2.4 on 2025-12-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.employee')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('log_type', models.CharField(choices=[('WORK', '工作'), ('MEETING', '会议'), ('COMMUNICATION', '沟通'), ('DEVELOPMENT', '开发'), ('STUDY', '学习')], max_length=20)),
                ('emotion_tag', models.CharField(blank=True, choices=[('ACTIVE', '积极'), ('FOCUSED', '专注'), ('SATISFIED', '满意'), ('TIRED', '疲惫')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': '日志条目',
                'verbose_name_plural': '日志条目',
                'db_table': 'log_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '日志标签',
                'verbose_name_plural': '日志标签',
                'db_table': 'log_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='log_app.logentry')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='log_app.logtag')),
            ],
            options={
                'verbose_name': '日志与标签关联',
                'verbose_name_plural': '日志与标签关联',
                'db_table': 'entry_tag_link',
                'managed': True,
                'unique_together': {('log_entry', 'tag')},
            },
        ),
    ]
