# Generated by Django 5.2.4 on 2025-12-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('work_id', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department_id', models.IntegerField(blank=True, db_column='department_id', null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('LEAVE', '请假')], default='ACTIVE', max_length=10)),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('pc_login_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='PC端登录Token')),
                ('mobile_login_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='移动端登录Token')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='dashboard.employee')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('employee_id', models.IntegerField(db_column='employee_id', primary_key=True, serialize=False, verbose_name='员工ID')),
                ('role_id', models.IntegerField(db_column='role_id', verbose_name='角色ID')),
            ],
            options={
                'verbose_name': '员工角色关联',
                'verbose_name_plural': '员工角色关联',
                'db_table': 'employee_role',
                'managed': True,
                'unique_together': {('employee_id', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyTopTaskConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_ids', models.JSONField(default=list, verbose_name='任务ID列表')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司十大任务配置',
                'verbose_name_plural': '公司十大任务配置',
                'db_table': 'company_top_task_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to='dashboard.employee')),
                ('can_view_all_tasks', models.BooleanField(default=False, verbose_name='查看所有任务')),
                ('can_view_all_logs', models.BooleanField(default=False, verbose_name='查看所有日志')),
            ],
            options={
                'verbose_name': '员工权限',
                'verbose_name_plural': '员工权限',
                'db_table': 'employee_permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalTopTaskConfig',
            fields=[
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_top_task_config', serialize=False, to='dashboard.employee')),
                ('task_ids', models.JSONField(default=list, verbose_name='任务ID列表')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人十大任务配置',
                'verbose_name_plural': '个人十大任务配置',
                'db_table': 'personal_top_task_config',
                'managed': True,
            },
        ),
    ]
