# Generated by Django 5.2.4 on 2025-12-23 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_employeepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to='dashboard.employee')),
                ('can_view_all_tasks', models.BooleanField(default=False, verbose_name='查看所有任务')),
                ('can_view_all_logs', models.BooleanField(default=False, verbose_name='查看所有日志')),
            ],
            options={
                'verbose_name': '员工权限',
                'verbose_name_plural': '员工权限',
                'db_table': 'employee_permission',
                'managed': True,
            },
        ),
    ]
