# Generated by Django 5.2.4 on 2025-12-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employeepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('priority', models.CharField(choices=[('NORMAL', '普通'), ('IMPORTANT', '重要'), ('URGENT', '紧急')], default='NORMAL', max_length=10, verbose_name='优先级')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='dashboard.employee')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'announcement',
                'ordering': ['-is_pinned', '-created_at'],
                'managed': True,
            },
        ),
    ]
