# Generated by Django 5.2.4 on 2025-12-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
