# Generated by Django 5.2.4 on 2025-12-23 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('group_id', models.AutoField(db_column='group_id', primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, verbose_name='提醒组名称')),
                ('group_type', models.CharField(choices=[('SMS', '短信'), ('EMAIL', '邮件')], max_length=5, verbose_name='提醒类型')),
            ],
            options={
                'verbose_name': '消息提醒组',
                'verbose_name_plural': '消息提醒组',
                'db_table': 'notification_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=6)),
                ('project_source', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.RESTRICT, related_name='created_tasks', to='dashboard.employee')),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='dashboard.employee')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'TO_DO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='TO_DO', max_length=11)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('task_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁版本号')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'managed': True,
                'unique_together': {('task_name', 'project_source')},
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('subtask_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task_app.task')),
                ('subtask_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'TO_DO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='TO_DO', max_length=11)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
                'db_table': 'subtask',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '任务通知关联',
                'verbose_name_plural': '任务通知关联',
                'db_table': 'task_notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskNotificationMessage',
            fields=[
                ('notification_id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('NEW_TASK', '新任务通知'), ('DUE_SOON', '即将到期提醒'), ('OVERDUE', '任务逾期提醒'), ('TASK_COMPLETED', '任务完成通知')], max_length=20, verbose_name='通知类型')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务通知消息',
                'verbose_name_plural': '任务通知消息',
                'db_table': 'task_notification_message',
                'ordering': ['-created_time'],
                'managed': True,
            },
        ),
    ]
