# Generated by Django 5.2.4 on 2025-12-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationgroup',
            options={'managed': True, 'verbose_name': '消息提醒组', 'verbose_name_plural': '消息提醒组'},
        ),
        migrations.AlterModelOptions(
            name='tasknotification',
            options={'managed': True, 'verbose_name': '任务通知关联', 'verbose_name_plural': '任务通知关联'},
        ),
        migrations.AlterModelOptions(
            name='tasknotificationmessage',
            options={'managed': True, 'ordering': ['-created_time'], 'verbose_name': '任务通知消息', 'verbose_name_plural': '任务通知消息'},
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
