# Generated by Django 5.2.4 on 2025-12-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_announcement'),
        ('task_app', '0003_alter_notificationgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='notification_group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.notificationgroup'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='task_app.task'),
        ),
        migrations.AddField(
            model_name='tasknotificationmessage',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.employee'),
        ),
        migrations.AddField(
            model_name='tasknotificationmessage',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task_app.task'),
        ),
        migrations.AlterUniqueTogether(
            name='tasknotification',
            unique_together={('task', 'notification_group')},
        ),
    ]
