# Generated by Django 5.2.4 on 2025-12-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisProfile',
            fields=[
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_analysis_profile', serialize=False, to='dashboard.employee')),
                ('ai_advice', models.TextField(blank=True, null=True, verbose_name='AI建议')),
                ('mbti_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='MBTI类型')),
                ('mbti_analysis', models.TextField(blank=True, null=True, verbose_name='MBTI分析')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI分析档案',
                'verbose_name_plural': 'AI分析档案',
                'db_table': 'ai_analysis_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiDeptAnalysisProfile',
            fields=[
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_dept_analysis_profiles', serialize=False, to='dashboard.department')),
                ('ai_advice', models.TextField(blank=True, null=True, verbose_name='部门AI建议')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门AI分析档案',
                'verbose_name_plural': '部门AI分析档案',
                'db_table': 'ai_dept_analysis_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiMbtiCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=5, verbose_name='MBTI类型')),
                ('content', models.TextField(verbose_name='分析内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_mbti_caches', to='dashboard.employee')),
            ],
            options={
                'verbose_name': 'MBTI分析缓存',
                'verbose_name_plural': 'MBTI分析缓存',
                'db_table': 'ai_mbti_cache',
                'managed': True,
                'indexes': [models.Index(fields=['employee', 'mbti_type'], name='ai_mbti_cac_employe_488fa8_idx')],
            },
        ),
    ]
