# Generated by Django 5.2.4 on 2025-12-23 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_delete_aimbticache'),
        ('dashboard', '0003_employeepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMbtiCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=5, verbose_name='MBTI类型')),
                ('content', models.TextField(verbose_name='分析内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_mbti_caches', to='dashboard.employee')),
            ],
            options={
                'verbose_name': 'MBTI分析缓存',
                'verbose_name_plural': 'MBTI分析缓存',
                'db_table': 'ai_mbti_cache',
                'managed': True,
                'indexes': [models.Index(fields=['employee', 'mbti_type'], name='ai_mbti_cac_employe_488fa8_idx')],
            },
        ),
    ]
